my_string=input("Какое настроение?")
print(my_string)
print(my_string.upper())
print(my_string.lower())
my_string=input("Какое настроение?".replace(" ", ""))
print(my_string[0])
print(my_string[-1])
